project:
  type: website
  output-dir: _site
  render:
    - "*.md"
    - "!help.md"
    - "talks/"
    - "!internal/"

website:
  title: "ðŸ”¬ Light-Sheet Image Analysis Workshop 2026"
  favicon: "media/lisium.svg"
  open-graph: true
  twitter-card: true
  site-url: https://bruvellu.github.io/light-sheet-image-analysis-workshop-2026
  repo-url: https://github.com/bruvellu/light-sheet-image-analysis-workshop-2026
  issue-url: https://github.com/bruvellu/light-sheet-image-analysis-workshop-2026/issues/new
  repo-actions: [edit, issue]
  page-navigation: true
  bread-crumbs: true
  search:
    show-item-context: true
    type: overlay
  page-footer:
    center:
      - text: "LiSIUM"
        href: https://lightsheetchile.cl/light-sheet-image-analysis-workshop-2026-2/

  navbar:
    tools:
      - icon: github
        href: https://github.com/bruvellu/light-sheet-image-analysis-workshop-2026
        text: GitHub

  sidebar:
    style: "floating"
    contents: auto

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    toc-depth: 4
    code-copy: true
    code-overflow: wrap
    lightbox: true

